mozilla/positron

- positron/components/ModuleLoader.jsm
- positron/components/PositronAppRunner.jsm
- positron/components/moz.build
- positron/node/lib/process.js
This branch makes the module loading module support multiple independent module loaders in preparation for injecting module loading into a renderer "process." (Say that ten times fast.)
> support multiple module loaders and process types

- positron/modules/atom_browser_web_contents.js
This warns instead of throwing an exception on `WebContents.openDevTools()`, so the "hello world" app continues after calling that method, and we can test a fix for #5.
> warn that WebContents.openDevTools() isn't implemented instead of throwing

- positron/modules/process.js
This is a comment-only change that will hopefully help someone looking into failures like the one you get when you try to run the Electron tests.
> explain atomBinding failures

- positron/modules/atom_browser_window.js
This branch implements the *BrowserWindow.close* and *app.window-all-closed* events, fixing #4 and #5.
> implement the BrowserWindow.close and app.window-all-closed events (fixes #4, #5)

- positron/components/ModuleLoader.jsm
- positron/components/Process.js
Recent changes broke exposure of the *process* global to BrowserWindow contexts. This fixes the problem.
> fix exposure of process global to window contexts

- devtools/client/framework/target-from-url.js
- devtools/client/framework/test/browser_target_from_url.js
- devtools/client/framework/toolbox-init.js
- devtools/server/actors/moz.build
- devtools/server/actors/root.js
- devtools/server/actors/window.js
- devtools/server/docs/actor-hierarchy.md
- devtools/shared/client/main.js
- positron/app/positron.js
- positron/confvars.sh
- positron/modules/atom_browser_web_contents.js
I've added support to open the DevTools when calling `BrowserWindow.webContents.openDevTools()` as in the example app (so this fixes #3).
I added some additional abilities to the tools for targeting specific windows directly to help with this case. I've kept all the `/devtools` changes in separate commits from `/positron` ones, for hopefully easier merging if bits are landed in m-c later.
~~The tools seems to be up and running in general, but there's a few rough edges for now, like you get a giant error on quit if the tools are still open. I figured I would resolve these things separately.~~ (Error on quit now resolved.)
@mykmelez, maybe you can review?
> First pass at DevTools for BrowserWindow

- positron/modules/atom_browser_window.js
After merging @jryans's devtools branch, I noticed this error when quitting the "hello world" app: `JavaScript error: … resource:///modules/gecko/atom_browser_window.js, line 71: TypeError: browserWindow is undefined`. Presumably it's because the observer gets a notification about the devtools window closing, but that window isn't a BrowserWindow, so it isn't found in `browserWindows`. Thus this branch ensures *browserWindow* before trying to use it.
> ensure browserWindow on domwindowclosed

- positron/modules/atom_browser_app.js
- positron/modules/atom_browser_web_contents.js
This fixes #29 so that calls to `quit()` after the browser window closes correctly ends the application on Linux (and hopefully Windows as well).
There is still a bit of mystery, as I don't entirely follow why the `unload` handler is needed to make this work. Happy to revise if anyone has ideas!
r? @mykmelez
> Close DevTools window on browser close

- devtools/client/devtools-startup.manifest
- toolkit/components/console/jsconsole-clhandler.manifest
@mykmelez, here's the `command-line-handler` ordering that should be upstreamable.
It seems to work for Positron and Firefox in my testing.
> Include DevTools command line handler via category entry

- devtools/client/devtools-startup.js
- devtools/server/actors/script.js
- devtools/server/actors/webbrowser.js
@jryans This works as expected when applied on top of #40. Is it something that DevTools might be willing take upstream? Perhaps in coordination with another flag like `--pause-jsdebugger-until-server-thread-resumes-even-if-that-means-hanging-the-app`?
Note: I do see two instances of this error after the server connects:
>Handler function threw an exception: TypeError: this._progressListener is undefined
>Stack: _onDocShellCreated/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/webbrowser.js:1319:9
>exports.makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:101:14
>Line: 1319, column: 9
> pause until debugger thread resumed so we can debug startup

- devtools/server/actors/chrome.js
@jryans: Here are a couple more places where this._progressListener is assumed, one of which I just hit:
>"Handler function DebuggerTransport.prototype.onInputStreamReady threw an exception: TypeError: this._progressListener is undefined
>Stack: ChromeActor.prototype._detach@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/chrome.js:149:5
>exit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/webbrowser.js:1125:9
>disconnect@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/webbrowser.js:1108:5
>AP_remove@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/common.js:263:7
>AP_destroy@resource://gre/modules/commonjs/toolkit/loader.js -> …
> ensure progress listener again

- positron/modules/atom_common_id_weak_map.js
@marcoscaceres The only difference from your suggested implementation is that *set* doesn't return `this`, because the upstream implementation doesn't do that:
https://github.com/electron/electron/blob/v0.37.8/atom/common/api/atom_api_id_weak_map.cc#L21-L25
> define IDWeakMap methods on its prototype

- devtools/client/framework/toolbox-init.js
@jryans While resolving conflicts with a merge from upstream, I noticed a few issues with toolbox-init:
1. The script tests `if (iframe)` after calling `iframe.QueryInterface()`, but that call should throw an exception if *iframe* is falsy, so the conditional will never be false.
2. After fixing issue #1 by testing *iframe* before calling `iframe.QueryInterface()`, if *iframe* is falsy, then *toolboxOpened* is never defined, so the `toolboxOpened.catch()` call below will fail.
3. The promise chain will reach the `toolboxOpened.then()` function even if there was an error opening the toolbox, since it gets attached to the chain after `toolboxOpened.catch()`, which doesn't re-throw the error.
Here are fixes for these issues.
> ensure iframe first; set toolboxOpened unconditionally; end after catch

- positron/components/PositronCLH.js
Instead of #52, we could take this approach to be more like Firefox's behavior.
So, for the "all" feature to apply correctly, `openWindow` must consider you to be a [`dialog`][1], where that is apparently defined as "passed a non-zero length args array".
And sure enough, Firefox's `nsBrowserContentHandler.js` has an [`openWindow`][2] wrapper which seems to create an args array and add at least one element down each of its various paths.
Perhaps it's best to match Firefox since this should enable many [features][3], instead of listing them one by one.
[2]: https://dxr.mozilla.org/mozilla-central/rev/46fe2115d46a5bb40523b8466341d8f9a26e1bdf/browser/components/nsBrowserContentHandler.js#178
[1]: https://dxr.mozilla.org/mozilla-central/rev/46fe2115d46a5bb40523b8466341d8f9a26e1bdf/embedding/com …
> Pass args to apply `all` window feature

- positron/components/ModuleLoader.jsm
- positron/components/Process.js
- positron/modules/process.js
- positron/webidl/Process.webidl
@marcoscaceres This is another step toward implementing *&lt;webview>*, as the modules that implement it (and the other modules that get loaded in the renderer process) all assume that their global object is the *DOMWindow* object for the renderer window, and they access a variety of *DOMWindow* built-ins on it.
Instead of identifying each individual built-in those modules use and then manually adding them to the global that the *ModuleLoader* creates, this branch makes the *DOMWindow* object itself be the global, so all of its built-ins are available to renderer process modules.
Doing this means that the *process* global for those objects is now the one we bind to *DOMWindow* via WebIDL, and that entrained some changes to the way we expose its properties and methods Basically: we had to …
> make the window object be the global object for modules in renderer processes

- devtools/server/actors/chrome.js
- devtools/server/actors/webbrowser.js
- positron/app/positron.js
- positron/components/Process.js
- positron/modules/atom_renderer_ipc.js
I was able to get around the issues from #48 by ensuring we always have a window, and during early startup, we can use the hidden window for that purpose. This allows us to revert the various `_progressListener` guards that were added recently.
Overall the tools are working much better now in the platform debugger. However, I did notice that typing in the console triggers autocompletion that seems to send things over Positron's IPC mechanism, but it fails for some reason. I did not work that part out yet, but added a small debugging aid to improve the error at least. Console evaluation should now be working, so you ignore these autocomplete errors for now.
Fixes #48. @mykmelez, want to take a look?
> Resolve window errors when platform debugging

- positron/modules/atom_browser_app.js
- positron/modules/atom_browser_debugger.js
- positron/modules/atom_browser_download_item.js
- positron/modules/atom_browser_menu.js
- positron/modules/atom_browser_session.js
- positron/modules/atom_browser_web_contents.js
- positron/modules/atom_browser_window.js
- positron/modules/atom_common_v8_util.js
- positron/modules/atom_renderer_web_frame.js
- positron/modules/buffer.js
- positron/modules/constants.js
- positron/modules/contextify.js
- positron/modules/fs.js
- positron/modules/fs_event_wrap.js
- positron/modules/moz.build
- positron/modules/positron_util.js
- positron/modules/process.js
- positron/modules/timer_wrap.js
This fixes #32 by adding _positronUtil.makeStub()_, which makes a "stub function" that warns the first time it's called, and then replacing all `function() { /* stub */ }` occurrences with functions created by *makeStub()*.
Modules that are themselves stubs call *makeStub()()* to make a stub function and then immediately call it to output a warning (so we see the warning when the module is first evaluated).
Stub functions that need to return a value pass the return value to *makeStub()*, which then returns it each time the stub is called (although it still only warns once). Stubs that need to generate a return value (or do something else when the stub is called) pass a function argument for the *returnValue* property, which the "warn once" function will then call to generate the return …
> warn once for each stub (fixes #32)

- positron/components/Process.js
- positron/modules/atom_browser_web_contents.js
- positron/modules/atom_browser_window.js
- positron/modules/process.js
- positron/webidl/Process.webidl
@brendandahl Now that you're hacking in Positron, perhaps you can review this change?  It's a prerequisite to supporting the sample browser app.
Currently, a _ModuleLoader_ is created for a _BrowserWindow_ when the _process_ global is accessed in the window. That's fine for the "hello world" app, which accesses that global. But the sample browser doesn't access _process_, and _process_ is actually lazily instantiated, which means that we don't currently create a _ModuleLoader_ for the sample browser's _BrowserWindow_.
And since the &lt;webview> element is initialized by Electron's web-view.js module, which gets loaded by the _ModuleLoader_, that means there's no &lt;webview> in the sample browser. Making the _process_ global create the _ModuleLoader_ was always a hack that we needed to …
> construct a module loader for every chrome window

- toolkit/xre/nsXREDirProvider.cpp
[Bug 1270356](https://bugzilla.mozilla.org/show_bug.cgi?id=1270356) adds a reference to GetOSXFolderType into nsXREDirProvider.cpp, which busts the build with:
```
In file included from /Users/myk/Projects/positron/obj-x86_64-apple-darwin14.5.0/toolkit/xre/Unified_cpp_toolkit_xre0.cpp:56:
/Users/myk/Projects/positron/toolkit/xre/nsXREDirProvider.cpp:257:8: error: use of undeclared identifier 'GetOSXFolderType'; did you mean 'GetFolderTypes'?
rv = GetOSXFolderType(kOnSystemDisk, kApplicationSupportFolderType, getter_AddRefs(localDir));
^~~~~~~~~~~~~~~~
GetFolderTypes
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Folders.h:745:1: note: …
```
> include SpecialSystemDirectory.h to resolve build bustage

- README.md
- build/moz.configure/init.configure
This makes Positron the default app, so you don't have to create a .mozconfig file to build it. That simplifies build instructions, which is handy for folks who are less familiar with Mozilla's build system. In particular, with this change, I can tell people to simply cut and paste a block of text into a terminal to get, build, and test Positron:
>git clone https://github.com/mozilla/positron
>cd positron
>./mach build
>./mach run positron/test/hello-world/
Whereas before I had to tell them to enable the app in .mozconfig, making it more cumbersome to follow the instructions, because they're no longer copy/pastable in one fell swoop:
>git clone https://github.com/mozilla/positron
>cd positron
>\# Now enable the app in .mozconfig: ac_add_options --enable-application=positron
>./mach build …
> Default app

- positron/modules/atom_browser_web_contents.js
The &lt;webview> isn't guaranteed to have a content document, so we should ensure it does before trying to get its URL.
> don't assume the webview has a content document

- dom/base/nsContentUtils.cpp
Upstream bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1281297
Fixes #82
> Fix webview focus.

- dom/base/nsDocument.cpp
- positron/electron/lib/renderer/web-view/web-view.js
After some careful log review of remote=true/false, I saw that there were some NS_FAILED that'd didn't occur on remote=false. After checking those out, I tracked the failure down to https://github.com/mozilla/gecko-dev/blob/965dbc5745f2dd40106a3e075ab8d3ef284c0aa6/caps/nsSystemPrincipal.cpp#L73
Turns out our hack to give system principal to the top document was also giving it to the remote iframe.
> Ensure remote iframes don't get the system principal.

- positron/modules/atom_browser_web_contents.js
The sample browser app still leaves a bit to be desired, but it seems to also have issues with electron as well (I see "undefined" flashed in the url bar when loading and changing pages).
Fixes #92
> Track the url of remote iframes.

- positron/components/ModuleLoader.jsm
- positron/electron/lib/browser/rpc-server.js
- positron/modules/process.js
This is a partial fix for #45 that coalesces sandboxes for the main process, reusing a single sandbox for all modules loaded in that process, so globals like *Object* return the expected results in cross-module equality comparisons. In the process, it removes the "duck typing" workaround that we landed in #26.
Sandbox coalescing for renderer processes still doesn't work, and I'm not sure why, but I've described the issue in #93, and this branch continues to use discrete sandboxes for each module loaded in that process.
I also updated some commentary and un-refactored *injectModuleGlobals*, which is only called at one site, and which is mis-named in any case.
@brendandahl How does this look to you?
> reuse sandbox for main process

- positron/components/ModuleLoader.jsm
- positron/modules/atom_browser_web_contents.js
Fixes #93 an #45
This solution doesn't seem quite as clean as using the built in loadSubScript and I  wonder about the performance implications of loading the entire script into a string and evaling it.
We could instead try to fix the DOM bindings issue I mentioned in https://github.com/mozilla/positron/issues/45#issuecomment-228914035
Thoughts?
> Load modules in their own scopes with evalInSandbox.

- positron/electron/lib/renderer/web-view/web-view.js
This doesn't manifest in the sample browser, strangely, perhaps because it applies some style rule to the iframe, but the &lt;iframe mozbrowser> in the shadow DOM of the &lt;webview> element is surrounded by a 2px border when a &lt;webview> is placed into a simple app without any other styling.
And since the &lt;iframe> is an internal implementation detail, it shouldn't express visible style. Apps that want a border around the &lt;webview> can always add one themselves. (Electron doesn't display such a border by default, so this change also improves Electron compatibility.)
> hide iframe border that Gecko adds by default

- .taskcluster.yml
This branch uses TaskCluster's support for GitHub to add continuous integration to Positron. Currently, it just builds the app, and TaskCluster reports the result via a comment on each change (or changeset) as well as an annotation on each pull request (I think; will know for sure once I create this pull request). In the future, we should be able to add tasks that run tests as well, once we have tests running.
This is essentially a wholesale replacement of the existing .taskcluster.yml file in the top-level of mozilla-central, so the [whole file view](https://github.com/mozilla/positron/blob/d84e9b0d9e6bd42d255d70a95bbd83608d783e04/.taskcluster.yml) is a better read than the default diff view. Unfortunately, we have to overload that file (and resolve spurious conflicts when merging from …
> replace .taskcluster.yml file with Positron-specific version

- positron/components/PositronAppRunner.jsm
- positron/modules/atom_browser_app.js
- positron/modules/atom_browser_menu.js
- positron/modules/atom_browser_window.js
- positron/modules/atom_common_global_shortcut.js
- positron/modules/atom_common_protocol.js
- positron/modules/moz.build
- positron/test/hello-world-server/main.js
- positron/test/hello-world-server/package.json
- positron/webidl/LICENSE
- positron/webidl/Makefile.in
- positron/webidl/NodeBindings.cpp
- positron/webidl/NodeBindings.h
- positron/webidl/NodeBindingsLinux.cpp
- positron/webidl/NodeBindingsLinux.h
- positron/webidl/NodeBindingsMac.cpp
- positron/webidl/NodeBindingsMac.h
- positron/webidl/NodeLoader.cpp
- positron/webidl/NodeLoader.h
- positron/webidl/moz.build
- positron/webidl/nsINodeLoader.idl
- toolkit/library/moz.build
@brendandahl This lands some fixes (mostly stubs) to improve support for Tofino on the node-integration branch.
It doesn't fix all issues, as there is still an error being thrown in Tofino's main process, and the browser process fails because it still requires Node there. But it does enable Tofino to open a BrowserWindow. It just doesn't yet load the browser's UI into it.
Some changes to Tofino were also required, and I've landed those in the support-positron branch of my Tofino fork (https://github.com/mykmelez/tofino/tree/support-positron). Most of the changes are just workarounds for `let (const of)`, which we can undo when we merge from upstream gecko-dev, where that's been implemented. Another change stubs out the use of a Node logging module that depends on a native module.
This …
> partially support tofino

- positron/components/PositronAppRunner.jsm
- positron/webidl/LICENSE
- positron/webidl/Makefile.in
- positron/webidl/NodeBindings.cpp
- positron/webidl/NodeBindings.h
- positron/webidl/NodeBindingsLinux.cpp
- positron/webidl/NodeBindingsLinux.h
- positron/webidl/NodeBindingsMac.cpp
- positron/webidl/NodeBindingsMac.h
- positron/webidl/NodeLoader.cpp
- positron/webidl/NodeLoader.h
- positron/webidl/moz.build
- positron/webidl/nsINodeLoader.idl
Event loop now runs and it's possible to do a hello world example with a server, but I'm currently getting a compartment mismatch crash on shutdown. I also have a have few TODO's in there that I'm still looking at to see if I need to address them.
example changes to hello world
```(diff)
+++ b/positron/test/hello-world/main.js
@@ -24,7 +24,7 @@ app.on('ready', function() {
mainWindow = new BrowserWindow({width: 800, height: 600});
// and load the index.html of the app.
-    mainWindow.loadURL('file://' + __dirname + '/index.html');
+    mainWindow.loadURL('http://localhost:8000');
// Open the DevTools.
mainWindow.webContents.openDevTools();
@@ -37,3 +37,15 @@ app.on('ready', function() {
mainWindow = null;
});
});
+
+// Load the http module to create an http server.
+var http = …
```
> [WIP] Fix the libuv event loop for mac and linux.

- positron/webidl/Makefile.in
@brendandahl I know you reverted this on #113, but it's worth landing early, while that branch is still a WIP.
The change reverts a fix I landed earlier for Windows, but Windows has bigger problems, and it isn't clear that the earlier fix will still be needed once those problems are resolved. So we might as well make life easier on Mac/Linux in the meantime.
> build specific type (reverts Windows fix)

- positron/config/mozconfig
- positron/config/mozconfig-debug
#122 was an incomplete cherry-pick that broke TaskCluster runs. This PR adds the two missing mozconfig files.
> finish cherry-picking taskcluster improvements by adding mozconfig files

- .gitmodules
- js/src/builtin/Error.js
- js/src/jsapi-tests/testSavedStacks.cpp
- js/src/jsapi.cpp
- js/src/jsapi.h
- js/src/vm/CommonPropertyNames.h
- js/src/vm/ErrorObject.cpp
- js/src/vm/Runtime.cpp
- js/src/vm/Runtime.h
- js/src/vm/SavedStacks.cpp
- positron/configure.in
This updates the positron-spidernode submodule and makes the necessary changes to build with the newer version (applies https://github.com/mozilla/spidernode/blob/master/deps/spidershim/spidermonkey-patches/03-v8-stack.patch, sets `--external-spidermonkey-has-nspr`).
It also sets the "branch" of the submodule to `master`, which is the branch of positron-spidernode that contains the changes to support Positron (now that I've merged https://github.com/mozilla/positron-spidernode/pull/6). It isn't clear what the submodule's "branch" setting does, but it seems like the right thing to do.
> update positron-spidernode submodule

- .gitmodules
This updates the positron/electron submodule to the latest tip of the submodule repository (now that I've merged https://github.com/mozilla/positron-electron/pull/1), which undoes a couple of workarounds that are no longer needed now that upstream Gecko implements `for (let … of …)` correctly.
It also sets the "branch" of the submodule to master, which seems like the right thing to do, even though it isn't clear what the submodule's "branch" setting does.
> update positron/electron submodule

- positron/config/mozconfig
I didn't notice this when I merged #152, but for some reason the Gecko merge produced a non-merge commit containing the diff between the two branches instead of a merge commit that add the upstream commits as a branch.
I have no idea why, since I didn't do anything unusual, just `git merge gecko-dev/master` (where "gecko-dev" is the name of the remote for https://github.com/mozilla/gecko-dev).
In any case, here's a merge commit that actually merges the branches. The command I invoked is the same, `git merge gecko-dev/master`, but the output is what I expected the first time around (and should have confirmed before merging the pull request).
On this branch, when I `git merge gecko-dev/master`, then Git says the branch is "Already up-to-date." So merging this branch should get things into a …
> merge upstream Gecko again
